---
- name: Check if CTFd repository is cloned
  stat:
    path: /home/unisinos/CTFd
  register: ctfd_repo

- name: Clone the CTFd repository if not already cloned
  git:
    repo: 'https://github.com/GabrielPrzybysz/CTFd.git'
    dest: /home/unisinos/CTFd
  when: not ctfd_repo.stat.exists

- name: Ensure CTFd Docker container is running
  docker_container:
    name: ctfd
    image: ctfd/ctfd
    state: started
    ports:
      - "8000:8000"
